export const data = JSON.parse("{\"key\":\"v-2acdc026\",\"path\":\"/composables/customQueries.html\",\"title\":\"Custom Queries\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"Features From VSF2 docs (https://docs.vuestorefront.io/v2/advanced/extending-graphql-queries.html), we can use custom query on existing APIS. Most of the apis use 'customQuery' ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://www.erpgap.com/composables/customQueries.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Custom Queries\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Features From VSF2 docs (https://docs.vuestorefront.io/v2/advanced/extending-graphql-queries.html), we can use custom query on existing APIS. Most of the apis use 'customQuery' ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.VSF\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Custom Queries\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.VSF\\\",\\\"url\\\":\\\"https://www.erpgap.com/\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Features\",\"slug\":\"features\",\"link\":\"#features\",\"children\":[{\"level\":3,\"title\":\"Use Cart\",\"slug\":\"use-cart\",\"link\":\"#use-cart\",\"children\":[]},{\"level\":3,\"title\":\"Use Category\",\"slug\":\"use-category\",\"link\":\"#use-category\",\"children\":[]},{\"level\":3,\"title\":\"Use CountrySearch\",\"slug\":\"use-countrysearch\",\"link\":\"#use-countrysearch\",\"children\":[]},{\"level\":3,\"title\":\"Use Facet\",\"slug\":\"use-facet\",\"link\":\"#use-facet\",\"children\":[]},{\"level\":3,\"title\":\"Use Password\",\"slug\":\"use-password\",\"link\":\"#use-password\",\"children\":[]},{\"level\":3,\"title\":\"Use Product\",\"slug\":\"use-product\",\"link\":\"#use-product\",\"children\":[]},{\"level\":3,\"title\":\"Use ProductVariant\",\"slug\":\"use-productvariant\",\"link\":\"#use-productvariant\",\"children\":[]},{\"level\":3,\"title\":\"Use Shipping\",\"slug\":\"use-shipping\",\"link\":\"#use-shipping\",\"children\":[]},{\"level\":3,\"title\":\"Use User\",\"slug\":\"use-user\",\"link\":\"#use-user\",\"children\":[]},{\"level\":3,\"title\":\"Use User Billing\",\"slug\":\"use-user-billing\",\"link\":\"#use-user-billing\",\"children\":[]},{\"level\":3,\"title\":\"Use Wishlist\",\"slug\":\"use-wishlist\",\"link\":\"#use-wishlist\",\"children\":[]},{\"level\":3,\"title\":\"Use Order\",\"slug\":\"use-order\",\"link\":\"#use-order\",\"children\":[]}]}],\"readingTime\":{\"minutes\":0.36,\"words\":109},\"filePathRelative\":\"composables/customQueries.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
