export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"a","t":"Presentation","i":"person-chalkboard"},["/README.md"]],
  ["v-2acdc026","/composables/customQueries.html",{"y":"a","t":"Custom Queries"},[":md"]],
  ["v-57089654","/composables/useCart.html",{"y":"a","t":"UseCart Composable"},[":md"]],
  ["v-34c309b6","/composables/useCategory.html",{"y":"a","t":"UseCategory Composable"},[":md"]],
  ["v-3ba21c80","/composables/useCountrySearch.html",{"y":"a","t":"UseCountrySearch Composable"},[":md"]],
  ["v-a9180772","/composables/useFacet.html",{"y":"a","t":"UseFacet Composable"},[":md"]],
  ["v-7f0bd110","/composables/useOrder.html",{"y":"a","t":"UseOrder Composable"},[":md"]],
  ["v-38fb0639","/composables/usePassword.html",{"y":"a","t":"UsePassword Composable"},[":md"]],
  ["v-19dc4acf","/composables/useProduct.html",{"y":"a","t":"UseProduct Composable"},[":md"]],
  ["v-617804de","/composables/useProductVariant.html",{"y":"a","t":"UseProductVariant Composable"},[":md"]],
  ["v-40f3d706","/composables/useShipping.html",{"y":"a","t":"UseShipping Composable"},[":md"]],
  ["v-9708dad6","/composables/useShippingProvider.html",{"y":"a","t":"UseShippingProvider Composable"},[":md"]],
  ["v-5e92d889","/composables/useUser.html",{"y":"a","t":"UseUser Composable"},[":md"]],
  ["v-3c8729ae","/composables/useUserBilling.html",{"y":"a","t":"UseUserBilling Composable"},[":md"]],
  ["v-021d1562","/composables/useWishlist.html",{"y":"a","t":"UseWishlist Composable"},[":md"]],
  ["v-2d83413f","/enviroment/",{"y":"a","t":"Guide","i":"lightbulb"},["/enviroment/README.md"]],
  ["v-004cf5bc","/enviroment/configuration.html",{"y":"a","t":"Configuration","i":"gear"},[":md"]],
  ["v-088c5e27","/enviroment/eco.html",{"y":"a","t":"Ecosystem","i":"server"},[":md"]],
  ["v-44951046","/enviroment/features.html",{"y":"a","t":"Features","i":"lock"},[":md"]],
  ["v-575b0790","/guides/customApis.html",{"y":"a","t":"Custom API client"},[":md"]],
  ["v-153abafa","/guides/customQueries.html",{"y":"a","t":"Custom queries"},[":md"]],
  ["v-7fefa255","/guides/imageHandle.html",{"y":"a","t":"Image handle"},[":md"]],
  ["v-786fc912","/guides/payment.html",{"y":"a","t":"Payment"},[":md"]],
  ["v-64703f5a","/introduction/demo.html",{"y":"a","t":"Demonstration","i":"file-lines"},[":md"]],
  ["v-5e48f3b3","/introduction/start.html",{"y":"a","t":"Quick Start","i":"play","I":0},[":md"]],
  ["v-5696e704","/reference/apiList.html",{"y":"a","t":"API"},[":md"]],
  ["v-2b6186bc","/reference/featureList.html",{"y":"a","t":"Feature List"},[":md"]],
  ["v-7c5ef2ef","/tips/customTypes.html",{"y":"a","t":"Custom types"},[":md"]],
  ["v-fcacb2c6","/tips/i18n.html",{"y":"a","t":"i18n"},[":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-07003d62","/composables/",{"y":"p","t":"Composables"},[]],
  ["v-ff762602","/guides/",{"y":"p","t":"Guides"},[]],
  ["v-712e14fc","/introduction/",{"y":"p","t":"Introduction"},[]],
  ["v-22a2f9fd","/reference/",{"y":"p","t":"Reference"},[]],
  ["v-1557149e","/tips/",{"y":"p","t":"Tips"},[]],
]
